// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxbdaydxfrkuyiepxzkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54YmRheWR4ZnJrdXlpZXB4emt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTA2MDIsImV4cCI6MjA2OTEyNjYwMn0.SjFE-yxp39p-8ziV2SZhi5f79M__sTlTSuFRaxbH7gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});